# For Development profile
spring:
  profiles:
    active: dev

logging:
  level:
    org:
      saggy:
        logbook: TRACE
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: TRACE
